// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface GetTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.GetTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The resource ID of the task to retrieve.
   * </pre>
   *
   * <code>string id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The resource ID of the task to retrieve.
   * </pre>
   *
   * <code>string id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve. An
   * unset value means the client does not impose any limit. A value of zero is
   * a request to not include any messages. The server MUST NOT return more
   * messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return Whether the historyLength field is set.
   */
  boolean hasHistoryLength();
  /**
   * <pre>
   * The maximum number of most recent messages from the task's history to retrieve. An
   * unset value means the client does not impose any limit. A value of zero is
   * a request to not include any messages. The server MUST NOT return more
   * messages than the provided value, but MAY apply a lower limit.
   * </pre>
   *
   * <code>optional int32 history_length = 3;</code>
   * @return The historyLength.
   */
  int getHistoryLength();
}
