// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface ListTaskPushNotificationConfigsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.ListTaskPushNotificationConfigsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The list of push notification configurations.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.TaskPushNotificationConfig configs = 1;</code>
   */
  java.util.List<io.a2a.grpc.TaskPushNotificationConfig> 
      getConfigsList();
  /**
   * <pre>
   * The list of push notification configurations.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.TaskPushNotificationConfig configs = 1;</code>
   */
  io.a2a.grpc.TaskPushNotificationConfig getConfigs(int index);
  /**
   * <pre>
   * The list of push notification configurations.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.TaskPushNotificationConfig configs = 1;</code>
   */
  int getConfigsCount();
  /**
   * <pre>
   * The list of push notification configurations.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.TaskPushNotificationConfig configs = 1;</code>
   */
  java.util.List<? extends io.a2a.grpc.TaskPushNotificationConfigOrBuilder> 
      getConfigsOrBuilderList();
  /**
   * <pre>
   * The list of push notification configurations.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.TaskPushNotificationConfig configs = 1;</code>
   */
  io.a2a.grpc.TaskPushNotificationConfigOrBuilder getConfigsOrBuilder(
      int index);

  /**
   * <pre>
   * A token to retrieve the next page of results, or empty if there are no more results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * A token to retrieve the next page of results, or empty if there are no more results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
