// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface ListTaskPushNotificationConfigsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.ListTaskPushNotificationConfigsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 4;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 4;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The parent task resource ID.
   * </pre>
   *
   * <code>string task_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The parent task resource ID.
   * </pre>
   *
   * <code>string task_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The maximum number of configurations to return.
   * </pre>
   *
   * <code>int32 page_size = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * A page token received from a previous `ListTaskPushNotificationConfigsRequest` call.
   * </pre>
   *
   * <code>string page_token = 3;</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * A page token received from a previous `ListTaskPushNotificationConfigsRequest` call.
   * </pre>
   *
   * <code>string page_token = 3;</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();
}
