// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface ListTasksRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.ListTasksRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * Filter tasks by context ID to get tasks from a specific conversation or session.
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * Filter tasks by context ID to get tasks from a specific conversation or session.
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * Filter tasks by their current status state.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskState status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * Filter tasks by their current status state.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskState status = 3;</code>
   * @return The status.
   */
  io.a2a.grpc.TaskState getStatus();

  /**
   * <pre>
   * The maximum number of tasks to return. The service may return fewer than this value.
   * If unspecified, at most 50 tasks will be returned.
   * The minimum value is 1.
   * The maximum value is 100.
   * </pre>
   *
   * <code>optional int32 page_size = 4;</code>
   * @return Whether the pageSize field is set.
   */
  boolean hasPageSize();
  /**
   * <pre>
   * The maximum number of tasks to return. The service may return fewer than this value.
   * If unspecified, at most 50 tasks will be returned.
   * The minimum value is 1.
   * The maximum value is 100.
   * </pre>
   *
   * <code>optional int32 page_size = 4;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * A page token, received from a previous `ListTasks` call.
   * `ListTasksResponse.next_page_token`.
   * Provide this to retrieve the subsequent page.
   * </pre>
   *
   * <code>string page_token = 5;</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * A page token, received from a previous `ListTasks` call.
   * `ListTasksResponse.next_page_token`.
   * Provide this to retrieve the subsequent page.
   * </pre>
   *
   * <code>string page_token = 5;</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <pre>
   * The maximum number of messages to include in each task's history.
   * </pre>
   *
   * <code>optional int32 history_length = 6;</code>
   * @return Whether the historyLength field is set.
   */
  boolean hasHistoryLength();
  /**
   * <pre>
   * The maximum number of messages to include in each task's history.
   * </pre>
   *
   * <code>optional int32 history_length = 6;</code>
   * @return The historyLength.
   */
  int getHistoryLength();

  /**
   * <pre>
   * Filter tasks which have a status updated after the provided timestamp in ISO 8601 format (e.g., "2023-10-27T10:00:00Z").
   * Only tasks with a status timestamp time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp status_timestamp_after = 7;</code>
   * @return Whether the statusTimestampAfter field is set.
   */
  boolean hasStatusTimestampAfter();
  /**
   * <pre>
   * Filter tasks which have a status updated after the provided timestamp in ISO 8601 format (e.g., "2023-10-27T10:00:00Z").
   * Only tasks with a status timestamp time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp status_timestamp_after = 7;</code>
   * @return The statusTimestampAfter.
   */
  com.google.protobuf.Timestamp getStatusTimestampAfter();
  /**
   * <pre>
   * Filter tasks which have a status updated after the provided timestamp in ISO 8601 format (e.g., "2023-10-27T10:00:00Z").
   * Only tasks with a status timestamp time greater than or equal to this value will be returned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp status_timestamp_after = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStatusTimestampAfterOrBuilder();

  /**
   * <pre>
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   * </pre>
   *
   * <code>optional bool include_artifacts = 8;</code>
   * @return Whether the includeArtifacts field is set.
   */
  boolean hasIncludeArtifacts();
  /**
   * <pre>
   * Whether to include artifacts in the returned tasks.
   * Defaults to false to reduce payload size.
   * </pre>
   *
   * <code>optional bool include_artifacts = 8;</code>
   * @return The includeArtifacts.
   */
  boolean getIncludeArtifacts();
}
