// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier (e.g. UUID) of the message. This is created by the message creator.
   * </pre>
   *
   * <code>string message_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <pre>
   * The unique identifier (e.g. UUID) of the message. This is created by the message creator.
   * </pre>
   *
   * <code>string message_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <pre>
   * Optional. The context id of the message. If set, the message will be associated with the given context.
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * Optional. The context id of the message. If set, the message will be associated with the given context.
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * Optional. The task id of the message. If set, the message will be associated with the given task.
   * </pre>
   *
   * <code>string task_id = 3;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * Optional. The task id of the message. If set, the message will be associated with the given task.
   * </pre>
   *
   * <code>string task_id = 3;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * Identifies the sender of the message.
   * </pre>
   *
   * <code>.lf.a2a.v1.Role role = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <pre>
   * Identifies the sender of the message.
   * </pre>
   *
   * <code>.lf.a2a.v1.Role role = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The role.
   */
  io.a2a.grpc.Role getRole();

  /**
   * <pre>
   * Parts is the container of the message content.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Part parts = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  java.util.List<io.a2a.grpc.Part> 
      getPartsList();
  /**
   * <pre>
   * Parts is the container of the message content.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Part parts = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.Part getParts(int index);
  /**
   * <pre>
   * Parts is the container of the message content.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Part parts = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  int getPartsCount();
  /**
   * <pre>
   * Parts is the container of the message content.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Part parts = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  java.util.List<? extends io.a2a.grpc.PartOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <pre>
   * Parts is the container of the message content.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Part parts = 5 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.PartOrBuilder getPartsOrBuilder(
      int index);

  /**
   * <pre>
   * Optional. Any metadata to provide along with the message.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional. Any metadata to provide along with the message.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional. Any metadata to provide along with the message.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Message.
   * </pre>
   *
   * <code>repeated string extensions = 7;</code>
   * @return A list containing the extensions.
   */
  java.util.List<java.lang.String>
      getExtensionsList();
  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Message.
   * </pre>
   *
   * <code>repeated string extensions = 7;</code>
   * @return The count of extensions.
   */
  int getExtensionsCount();
  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Message.
   * </pre>
   *
   * <code>repeated string extensions = 7;</code>
   * @param index The index of the element to return.
   * @return The extensions at the given index.
   */
  java.lang.String getExtensions(int index);
  /**
   * <pre>
   * The URIs of extensions that are present or contributed to this Message.
   * </pre>
   *
   * <code>repeated string extensions = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the extensions at the given index.
   */
  com.google.protobuf.ByteString
      getExtensionsBytes(int index);

  /**
   * <pre>
   * A list of task IDs that this message references for additional context.
   * </pre>
   *
   * <code>repeated string reference_task_ids = 8;</code>
   * @return A list containing the referenceTaskIds.
   */
  java.util.List<java.lang.String>
      getReferenceTaskIdsList();
  /**
   * <pre>
   * A list of task IDs that this message references for additional context.
   * </pre>
   *
   * <code>repeated string reference_task_ids = 8;</code>
   * @return The count of referenceTaskIds.
   */
  int getReferenceTaskIdsCount();
  /**
   * <pre>
   * A list of task IDs that this message references for additional context.
   * </pre>
   *
   * <code>repeated string reference_task_ids = 8;</code>
   * @param index The index of the element to return.
   * @return The referenceTaskIds at the given index.
   */
  java.lang.String getReferenceTaskIds(int index);
  /**
   * <pre>
   * A list of task IDs that this message references for additional context.
   * </pre>
   *
   * <code>repeated string reference_task_ids = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the referenceTaskIds at the given index.
   */
  com.google.protobuf.ByteString
      getReferenceTaskIdsBytes(int index);
}
