// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SubscribeToTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.SubscribeToTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional. Tenant ID, provided as a path parameter.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The resource ID of the task to subscribe to.
   * </pre>
   *
   * <code>string id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The resource ID of the task to subscribe to.
   * </pre>
   *
   * <code>string id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
