// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface TaskPushNotificationConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.TaskPushNotificationConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Tenant ID.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional. Tenant ID.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The ID of the task this configuration is associated with.
   * </pre>
   *
   * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The ID of the task this configuration is associated with.
   * </pre>
   *
   * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The push notification configuration details.
   * </pre>
   *
   * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the pushNotificationConfig field is set.
   */
  boolean hasPushNotificationConfig();
  /**
   * <pre>
   * The push notification configuration details.
   * </pre>
   *
   * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The pushNotificationConfig.
   */
  io.a2a.grpc.PushNotificationConfig getPushNotificationConfig();
  /**
   * <pre>
   * The push notification configuration details.
   * </pre>
   *
   * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder();
}
