// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface TaskStatusUpdateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.TaskStatusUpdateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the task that has changed.
   * </pre>
   *
   * <code>string task_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The ID of the task that has changed.
   * </pre>
   *
   * <code>string task_id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The ID of the context that the task belongs to.
   * </pre>
   *
   * <code>string context_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * The ID of the context that the task belongs to.
   * </pre>
   *
   * <code>string context_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * The new status of the task.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * The new status of the task.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The status.
   */
  io.a2a.grpc.TaskStatus getStatus();
  /**
   * <pre>
   * The new status of the task.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.TaskStatusOrBuilder getStatusOrBuilder();

  /**
   * <pre>
   * Optional. Metadata associated with the task update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional. Metadata associated with the task update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * Optional. Metadata associated with the task update.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
