// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package io.a2a.grpc;

/**
 * <pre>
 * A container associating a push notification configuration with a specific task.
 * </pre>
 *
 * Protobuf type {@code lf.a2a.v1.TaskPushNotificationConfig}
 */
@com.google.protobuf.Generated
public final class TaskPushNotificationConfig extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:lf.a2a.v1.TaskPushNotificationConfig)
    TaskPushNotificationConfigOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "TaskPushNotificationConfig");
  }
  // Use TaskPushNotificationConfig.newBuilder() to construct.
  private TaskPushNotificationConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TaskPushNotificationConfig() {
    tenant_ = "";
    taskId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_lf_a2a_v1_TaskPushNotificationConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_lf_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.TaskPushNotificationConfig.class, io.a2a.grpc.TaskPushNotificationConfig.Builder.class);
  }

  private int bitField0_;
  public static final int TENANT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenant_ = "";
  /**
   * <pre>
   * Optional. Tenant ID.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  @java.lang.Override
  public java.lang.String getTenant() {
    java.lang.Object ref = tenant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenant_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. Tenant ID.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantBytes() {
    java.lang.Object ref = tenant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object taskId_ = "";
  /**
   * <pre>
   * The ID of the task this configuration is associated with.
   * </pre>
   *
   * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the task this configuration is associated with.
   * </pre>
   *
   * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUSH_NOTIFICATION_CONFIG_FIELD_NUMBER = 3;
  private io.a2a.grpc.PushNotificationConfig pushNotificationConfig_;
  /**
   * <pre>
   * The push notification configuration details.
   * </pre>
   *
   * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the pushNotificationConfig field is set.
   */
  @java.lang.Override
  public boolean hasPushNotificationConfig() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The push notification configuration details.
   * </pre>
   *
   * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The pushNotificationConfig.
   */
  @java.lang.Override
  public io.a2a.grpc.PushNotificationConfig getPushNotificationConfig() {
    return pushNotificationConfig_ == null ? io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
  }
  /**
   * <pre>
   * The push notification configuration details.
   * </pre>
   *
   * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder() {
    return pushNotificationConfig_ == null ? io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenant_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, tenant_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, taskId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getPushNotificationConfig());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenant_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tenant_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, taskId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPushNotificationConfig());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.TaskPushNotificationConfig)) {
      return super.equals(obj);
    }
    io.a2a.grpc.TaskPushNotificationConfig other = (io.a2a.grpc.TaskPushNotificationConfig) obj;

    if (!getTenant()
        .equals(other.getTenant())) return false;
    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (hasPushNotificationConfig() != other.hasPushNotificationConfig()) return false;
    if (hasPushNotificationConfig()) {
      if (!getPushNotificationConfig()
          .equals(other.getPushNotificationConfig())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_FIELD_NUMBER;
    hash = (53 * hash) + getTenant().hashCode();
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    if (hasPushNotificationConfig()) {
      hash = (37 * hash) + PUSH_NOTIFICATION_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getPushNotificationConfig().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.TaskPushNotificationConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.TaskPushNotificationConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.TaskPushNotificationConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.TaskPushNotificationConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A container associating a push notification configuration with a specific task.
   * </pre>
   *
   * Protobuf type {@code lf.a2a.v1.TaskPushNotificationConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lf.a2a.v1.TaskPushNotificationConfig)
      io.a2a.grpc.TaskPushNotificationConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_lf_a2a_v1_TaskPushNotificationConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_lf_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.TaskPushNotificationConfig.class, io.a2a.grpc.TaskPushNotificationConfig.Builder.class);
    }

    // Construct using io.a2a.grpc.TaskPushNotificationConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPushNotificationConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenant_ = "";
      taskId_ = "";
      pushNotificationConfig_ = null;
      if (pushNotificationConfigBuilder_ != null) {
        pushNotificationConfigBuilder_.dispose();
        pushNotificationConfigBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_lf_a2a_v1_TaskPushNotificationConfig_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.TaskPushNotificationConfig getDefaultInstanceForType() {
      return io.a2a.grpc.TaskPushNotificationConfig.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.TaskPushNotificationConfig build() {
      io.a2a.grpc.TaskPushNotificationConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.TaskPushNotificationConfig buildPartial() {
      io.a2a.grpc.TaskPushNotificationConfig result = new io.a2a.grpc.TaskPushNotificationConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.TaskPushNotificationConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenant_ = tenant_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.taskId_ = taskId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pushNotificationConfig_ = pushNotificationConfigBuilder_ == null
            ? pushNotificationConfig_
            : pushNotificationConfigBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.TaskPushNotificationConfig) {
        return mergeFrom((io.a2a.grpc.TaskPushNotificationConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.TaskPushNotificationConfig other) {
      if (other == io.a2a.grpc.TaskPushNotificationConfig.getDefaultInstance()) return this;
      if (!other.getTenant().isEmpty()) {
        tenant_ = other.tenant_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasPushNotificationConfig()) {
        mergePushNotificationConfig(other.getPushNotificationConfig());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tenant_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              taskId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPushNotificationConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tenant_ = "";
    /**
     * <pre>
     * Optional. Tenant ID.
     * </pre>
     *
     * <code>string tenant = 1;</code>
     * @return The tenant.
     */
    public java.lang.String getTenant() {
      java.lang.Object ref = tenant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. Tenant ID.
     * </pre>
     *
     * <code>string tenant = 1;</code>
     * @return The bytes for tenant.
     */
    public com.google.protobuf.ByteString
        getTenantBytes() {
      java.lang.Object ref = tenant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. Tenant ID.
     * </pre>
     *
     * <code>string tenant = 1;</code>
     * @param value The tenant to set.
     * @return This builder for chaining.
     */
    public Builder setTenant(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenant_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Tenant ID.
     * </pre>
     *
     * <code>string tenant = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenant() {
      tenant_ = getDefaultInstance().getTenant();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. Tenant ID.
     * </pre>
     *
     * <code>string tenant = 1;</code>
     * @param value The bytes for tenant to set.
     * @return This builder for chaining.
     */
    public Builder setTenantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenant_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <pre>
     * The ID of the task this configuration is associated with.
     * </pre>
     *
     * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the task this configuration is associated with.
     * </pre>
     *
     * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the task this configuration is associated with.
     * </pre>
     *
     * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      taskId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the task this configuration is associated with.
     * </pre>
     *
     * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      taskId_ = getDefaultInstance().getTaskId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the task this configuration is associated with.
     * </pre>
     *
     * <code>string task_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      taskId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private io.a2a.grpc.PushNotificationConfig pushNotificationConfig_;
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.PushNotificationConfig, io.a2a.grpc.PushNotificationConfig.Builder, io.a2a.grpc.PushNotificationConfigOrBuilder> pushNotificationConfigBuilder_;
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the pushNotificationConfig field is set.
     */
    public boolean hasPushNotificationConfig() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The pushNotificationConfig.
     */
    public io.a2a.grpc.PushNotificationConfig getPushNotificationConfig() {
      if (pushNotificationConfigBuilder_ == null) {
        return pushNotificationConfig_ == null ? io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
      } else {
        return pushNotificationConfigBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPushNotificationConfig(io.a2a.grpc.PushNotificationConfig value) {
      if (pushNotificationConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pushNotificationConfig_ = value;
      } else {
        pushNotificationConfigBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setPushNotificationConfig(
        io.a2a.grpc.PushNotificationConfig.Builder builderForValue) {
      if (pushNotificationConfigBuilder_ == null) {
        pushNotificationConfig_ = builderForValue.build();
      } else {
        pushNotificationConfigBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergePushNotificationConfig(io.a2a.grpc.PushNotificationConfig value) {
      if (pushNotificationConfigBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          pushNotificationConfig_ != null &&
          pushNotificationConfig_ != io.a2a.grpc.PushNotificationConfig.getDefaultInstance()) {
          getPushNotificationConfigBuilder().mergeFrom(value);
        } else {
          pushNotificationConfig_ = value;
        }
      } else {
        pushNotificationConfigBuilder_.mergeFrom(value);
      }
      if (pushNotificationConfig_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearPushNotificationConfig() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pushNotificationConfig_ = null;
      if (pushNotificationConfigBuilder_ != null) {
        pushNotificationConfigBuilder_.dispose();
        pushNotificationConfigBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.PushNotificationConfig.Builder getPushNotificationConfigBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetPushNotificationConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder() {
      if (pushNotificationConfigBuilder_ != null) {
        return pushNotificationConfigBuilder_.getMessageOrBuilder();
      } else {
        return pushNotificationConfig_ == null ?
            io.a2a.grpc.PushNotificationConfig.getDefaultInstance() : pushNotificationConfig_;
      }
    }
    /**
     * <pre>
     * The push notification configuration details.
     * </pre>
     *
     * <code>.lf.a2a.v1.PushNotificationConfig push_notification_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.PushNotificationConfig, io.a2a.grpc.PushNotificationConfig.Builder, io.a2a.grpc.PushNotificationConfigOrBuilder> 
        internalGetPushNotificationConfigFieldBuilder() {
      if (pushNotificationConfigBuilder_ == null) {
        pushNotificationConfigBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.PushNotificationConfig, io.a2a.grpc.PushNotificationConfig.Builder, io.a2a.grpc.PushNotificationConfigOrBuilder>(
                getPushNotificationConfig(),
                getParentForChildren(),
                isClean());
        pushNotificationConfig_ = null;
      }
      return pushNotificationConfigBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:lf.a2a.v1.TaskPushNotificationConfig)
  }

  // @@protoc_insertion_point(class_scope:lf.a2a.v1.TaskPushNotificationConfig)
  private static final io.a2a.grpc.TaskPushNotificationConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.TaskPushNotificationConfig();
  }

  public static io.a2a.grpc.TaskPushNotificationConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskPushNotificationConfig>
      PARSER = new com.google.protobuf.AbstractParser<TaskPushNotificationConfig>() {
    @java.lang.Override
    public TaskPushNotificationConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TaskPushNotificationConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskPushNotificationConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.TaskPushNotificationConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

