// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.grpc;

@com.google.protobuf.Generated
public interface OAuthFlowsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.OAuthFlows)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Configuration for the OAuth Authorization Code flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   * @return Whether the authorizationCode field is set.
   */
  boolean hasAuthorizationCode();
  /**
   * <pre>
   * Configuration for the OAuth Authorization Code flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   * @return The authorizationCode.
   */
  org.a2aproject.sdk.grpc.AuthorizationCodeOAuthFlow getAuthorizationCode();
  /**
   * <pre>
   * Configuration for the OAuth Authorization Code flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1;</code>
   */
  org.a2aproject.sdk.grpc.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder();

  /**
   * <pre>
   * Configuration for the OAuth Client Credentials flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   * @return Whether the clientCredentials field is set.
   */
  boolean hasClientCredentials();
  /**
   * <pre>
   * Configuration for the OAuth Client Credentials flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   * @return The clientCredentials.
   */
  org.a2aproject.sdk.grpc.ClientCredentialsOAuthFlow getClientCredentials();
  /**
   * <pre>
   * Configuration for the OAuth Client Credentials flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2;</code>
   */
  org.a2aproject.sdk.grpc.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder();

  /**
   * <pre>
   * Deprecated: Use Authorization Code + PKCE instead.
   * </pre>
   *
   * <code>.lf.a2a.v1.ImplicitOAuthFlow implicit = 3 [deprecated = true];</code>
   * @deprecated lf.a2a.v1.OAuthFlows.implicit is deprecated.
   *     See a2a.proto;l=569
   * @return Whether the implicit field is set.
   */
  @java.lang.Deprecated boolean hasImplicit();
  /**
   * <pre>
   * Deprecated: Use Authorization Code + PKCE instead.
   * </pre>
   *
   * <code>.lf.a2a.v1.ImplicitOAuthFlow implicit = 3 [deprecated = true];</code>
   * @deprecated lf.a2a.v1.OAuthFlows.implicit is deprecated.
   *     See a2a.proto;l=569
   * @return The implicit.
   */
  @java.lang.Deprecated org.a2aproject.sdk.grpc.ImplicitOAuthFlow getImplicit();
  /**
   * <pre>
   * Deprecated: Use Authorization Code + PKCE instead.
   * </pre>
   *
   * <code>.lf.a2a.v1.ImplicitOAuthFlow implicit = 3 [deprecated = true];</code>
   */
  @java.lang.Deprecated org.a2aproject.sdk.grpc.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder();

  /**
   * <pre>
   * Deprecated: Use Authorization Code + PKCE or Device Code.
   * </pre>
   *
   * <code>.lf.a2a.v1.PasswordOAuthFlow password = 4 [deprecated = true];</code>
   * @deprecated lf.a2a.v1.OAuthFlows.password is deprecated.
   *     See a2a.proto;l=571
   * @return Whether the password field is set.
   */
  @java.lang.Deprecated boolean hasPassword();
  /**
   * <pre>
   * Deprecated: Use Authorization Code + PKCE or Device Code.
   * </pre>
   *
   * <code>.lf.a2a.v1.PasswordOAuthFlow password = 4 [deprecated = true];</code>
   * @deprecated lf.a2a.v1.OAuthFlows.password is deprecated.
   *     See a2a.proto;l=571
   * @return The password.
   */
  @java.lang.Deprecated org.a2aproject.sdk.grpc.PasswordOAuthFlow getPassword();
  /**
   * <pre>
   * Deprecated: Use Authorization Code + PKCE or Device Code.
   * </pre>
   *
   * <code>.lf.a2a.v1.PasswordOAuthFlow password = 4 [deprecated = true];</code>
   */
  @java.lang.Deprecated org.a2aproject.sdk.grpc.PasswordOAuthFlowOrBuilder getPasswordOrBuilder();

  /**
   * <pre>
   * Configuration for the OAuth Device Code flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.DeviceCodeOAuthFlow device_code = 5;</code>
   * @return Whether the deviceCode field is set.
   */
  boolean hasDeviceCode();
  /**
   * <pre>
   * Configuration for the OAuth Device Code flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.DeviceCodeOAuthFlow device_code = 5;</code>
   * @return The deviceCode.
   */
  org.a2aproject.sdk.grpc.DeviceCodeOAuthFlow getDeviceCode();
  /**
   * <pre>
   * Configuration for the OAuth Device Code flow.
   * </pre>
   *
   * <code>.lf.a2a.v1.DeviceCodeOAuthFlow device_code = 5;</code>
   */
  org.a2aproject.sdk.grpc.DeviceCodeOAuthFlowOrBuilder getDeviceCodeOrBuilder();

  org.a2aproject.sdk.grpc.OAuthFlows.FlowCase getFlowCase();
}
