// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.grpc;

@com.google.protobuf.Generated
public interface SecurityRequirementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.SecurityRequirement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A map of security schemes to the required scopes.
   * </pre>
   *
   * <code>map&lt;string, .lf.a2a.v1.StringList&gt; schemes = 1;</code>
   */
  int getSchemesCount();
  /**
   * <pre>
   * A map of security schemes to the required scopes.
   * </pre>
   *
   * <code>map&lt;string, .lf.a2a.v1.StringList&gt; schemes = 1;</code>
   */
  boolean containsSchemes(
      java.lang.String key);
  /**
   * Use {@link #getSchemesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.a2aproject.sdk.grpc.StringList>
  getSchemes();
  /**
   * <pre>
   * A map of security schemes to the required scopes.
   * </pre>
   *
   * <code>map&lt;string, .lf.a2a.v1.StringList&gt; schemes = 1;</code>
   */
  java.util.Map<java.lang.String, org.a2aproject.sdk.grpc.StringList>
  getSchemesMap();
  /**
   * <pre>
   * A map of security schemes to the required scopes.
   * </pre>
   *
   * <code>map&lt;string, .lf.a2a.v1.StringList&gt; schemes = 1;</code>
   */
  /* nullable */
org.a2aproject.sdk.grpc.StringList getSchemesOrDefault(
      java.lang.String key,
      /* nullable */
org.a2aproject.sdk.grpc.StringList defaultValue);
  /**
   * <pre>
   * A map of security schemes to the required scopes.
   * </pre>
   *
   * <code>map&lt;string, .lf.a2a.v1.StringList&gt; schemes = 1;</code>
   */
  org.a2aproject.sdk.grpc.StringList getSchemesOrThrow(
      java.lang.String key);
}
