// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.grpc;

@com.google.protobuf.Generated
public interface SendMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.SendMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The task created or updated by the message.
   * </pre>
   *
   * <code>.lf.a2a.v1.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <pre>
   * The task created or updated by the message.
   * </pre>
   *
   * <code>.lf.a2a.v1.Task task = 1;</code>
   * @return The task.
   */
  org.a2aproject.sdk.grpc.Task getTask();
  /**
   * <pre>
   * The task created or updated by the message.
   * </pre>
   *
   * <code>.lf.a2a.v1.Task task = 1;</code>
   */
  org.a2aproject.sdk.grpc.TaskOrBuilder getTaskOrBuilder();

  /**
   * <pre>
   * A message from the agent.
   * </pre>
   *
   * <code>.lf.a2a.v1.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <pre>
   * A message from the agent.
   * </pre>
   *
   * <code>.lf.a2a.v1.Message message = 2;</code>
   * @return The message.
   */
  org.a2aproject.sdk.grpc.Message getMessage();
  /**
   * <pre>
   * A message from the agent.
   * </pre>
   *
   * <code>.lf.a2a.v1.Message message = 2;</code>
   */
  org.a2aproject.sdk.grpc.MessageOrBuilder getMessageOrBuilder();

  org.a2aproject.sdk.grpc.SendMessageResponse.PayloadCase getPayloadCase();
}
