// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.grpc;

@com.google.protobuf.Generated
public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A Task object containing the current state of the task.
   * </pre>
   *
   * <code>.lf.a2a.v1.Task task = 1;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <pre>
   * A Task object containing the current state of the task.
   * </pre>
   *
   * <code>.lf.a2a.v1.Task task = 1;</code>
   * @return The task.
   */
  org.a2aproject.sdk.grpc.Task getTask();
  /**
   * <pre>
   * A Task object containing the current state of the task.
   * </pre>
   *
   * <code>.lf.a2a.v1.Task task = 1;</code>
   */
  org.a2aproject.sdk.grpc.TaskOrBuilder getTaskOrBuilder();

  /**
   * <pre>
   * A Message object containing a message from the agent.
   * </pre>
   *
   * <code>.lf.a2a.v1.Message message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <pre>
   * A Message object containing a message from the agent.
   * </pre>
   *
   * <code>.lf.a2a.v1.Message message = 2;</code>
   * @return The message.
   */
  org.a2aproject.sdk.grpc.Message getMessage();
  /**
   * <pre>
   * A Message object containing a message from the agent.
   * </pre>
   *
   * <code>.lf.a2a.v1.Message message = 2;</code>
   */
  org.a2aproject.sdk.grpc.MessageOrBuilder getMessageOrBuilder();

  /**
   * <pre>
   * An event indicating a task status update.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatusUpdateEvent status_update = 3;</code>
   * @return Whether the statusUpdate field is set.
   */
  boolean hasStatusUpdate();
  /**
   * <pre>
   * An event indicating a task status update.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatusUpdateEvent status_update = 3;</code>
   * @return The statusUpdate.
   */
  org.a2aproject.sdk.grpc.TaskStatusUpdateEvent getStatusUpdate();
  /**
   * <pre>
   * An event indicating a task status update.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatusUpdateEvent status_update = 3;</code>
   */
  org.a2aproject.sdk.grpc.TaskStatusUpdateEventOrBuilder getStatusUpdateOrBuilder();

  /**
   * <pre>
   * An event indicating a task artifact update.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;</code>
   * @return Whether the artifactUpdate field is set.
   */
  boolean hasArtifactUpdate();
  /**
   * <pre>
   * An event indicating a task artifact update.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;</code>
   * @return The artifactUpdate.
   */
  org.a2aproject.sdk.grpc.TaskArtifactUpdateEvent getArtifactUpdate();
  /**
   * <pre>
   * An event indicating a task artifact update.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4;</code>
   */
  org.a2aproject.sdk.grpc.TaskArtifactUpdateEventOrBuilder getArtifactUpdateOrBuilder();

  org.a2aproject.sdk.grpc.StreamResponse.PayloadCase getPayloadCase();
}
