// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.grpc;

@com.google.protobuf.Generated
public interface TaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.Task)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the task, generated by the server for a
   * new task.
   * </pre>
   *
   * <code>string id = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages).
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The contextId.
   */
  java.lang.String getContextId();
  /**
   * <pre>
   * Unique identifier (e.g. UUID) for the contextual collection of interactions
   * (tasks and messages).
   * </pre>
   *
   * <code>string context_id = 2;</code>
   * @return The bytes for contextId.
   */
  com.google.protobuf.ByteString
      getContextIdBytes();

  /**
   * <pre>
   * The current status of a `Task`, including `state` and a `message`.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * The current status of a `Task`, including `state` and a `message`.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The status.
   */
  org.a2aproject.sdk.grpc.TaskStatus getStatus();
  /**
   * <pre>
   * The current status of a `Task`, including `state` and a `message`.
   * </pre>
   *
   * <code>.lf.a2a.v1.TaskStatus status = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  org.a2aproject.sdk.grpc.TaskStatusOrBuilder getStatusOrBuilder();

  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  java.util.List<org.a2aproject.sdk.grpc.Artifact> 
      getArtifactsList();
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  org.a2aproject.sdk.grpc.Artifact getArtifacts(int index);
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  int getArtifactsCount();
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  java.util.List<? extends org.a2aproject.sdk.grpc.ArtifactOrBuilder> 
      getArtifactsOrBuilderList();
  /**
   * <pre>
   * A set of output artifacts for a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Artifact artifacts = 4;</code>
   */
  org.a2aproject.sdk.grpc.ArtifactOrBuilder getArtifactsOrBuilder(
      int index);

  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  java.util.List<org.a2aproject.sdk.grpc.Message> 
      getHistoryList();
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  org.a2aproject.sdk.grpc.Message getHistory(int index);
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  int getHistoryCount();
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  java.util.List<? extends org.a2aproject.sdk.grpc.MessageOrBuilder> 
      getHistoryOrBuilderList();
  /**
   * <pre>
   * protolint:disable REPEATED_FIELD_NAMES_PLURALIZED
   * The history of interactions from a `Task`.
   * </pre>
   *
   * <code>repeated .lf.a2a.v1.Message history = 5;</code>
   */
  org.a2aproject.sdk.grpc.MessageOrBuilder getHistoryOrBuilder(
      int index);

  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <pre>
   * protolint:enable REPEATED_FIELD_NAMES_PLURALIZED
   * A key/value object to store custom metadata about a task.
   * </pre>
   *
   * <code>.google.protobuf.Struct metadata = 6;</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
