// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.33.1

package org.a2aproject.sdk.grpc;

@com.google.protobuf.Generated
public interface TaskPushNotificationConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lf.a2a.v1.TaskPushNotificationConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional. Tenant ID.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The tenant.
   */
  java.lang.String getTenant();
  /**
   * <pre>
   * Optional. Tenant ID.
   * </pre>
   *
   * <code>string tenant = 1;</code>
   * @return The bytes for tenant.
   */
  com.google.protobuf.ByteString
      getTenantBytes();

  /**
   * <pre>
   * The push notification configuration details.
   * A unique identifier (e.g. UUID) for this push notification configuration.
   * </pre>
   *
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The push notification configuration details.
   * A unique identifier (e.g. UUID) for this push notification configuration.
   * </pre>
   *
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The ID of the task this configuration is associated with.
   * </pre>
   *
   * <code>string task_id = 3;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <pre>
   * The ID of the task this configuration is associated with.
   * </pre>
   *
   * <code>string task_id = 3;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * The URL where the notification should be sent.
   * </pre>
   *
   * <code>string url = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The URL where the notification should be sent.
   * </pre>
   *
   * <code>string url = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * A token unique for this task or session.
   * </pre>
   *
   * <code>string token = 5;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * A token unique for this task or session.
   * </pre>
   *
   * <code>string token = 5;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <pre>
   * Authentication information required to send the notification.
   * </pre>
   *
   * <code>.lf.a2a.v1.AuthenticationInfo authentication = 6;</code>
   * @return Whether the authentication field is set.
   */
  boolean hasAuthentication();
  /**
   * <pre>
   * Authentication information required to send the notification.
   * </pre>
   *
   * <code>.lf.a2a.v1.AuthenticationInfo authentication = 6;</code>
   * @return The authentication.
   */
  org.a2aproject.sdk.grpc.AuthenticationInfo getAuthentication();
  /**
   * <pre>
   * Authentication information required to send the notification.
   * </pre>
   *
   * <code>.lf.a2a.v1.AuthenticationInfo authentication = 6;</code>
   */
  org.a2aproject.sdk.grpc.AuthenticationInfoOrBuilder getAuthenticationOrBuilder();
}
