name: Build with '-Prelease'

on:
  pull_request:
    paths-ignore:
      - '**/docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build with -Prelease
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with release profile
        run: >
          mvn -B install
          -P release
          -DskipTests
          -Dgpg.skip=true
          -Drelease.auto.publish=false
